FROM ubuntu:16.04
	LABEL maintainer starovoytovsergeya@gmail.com
	RUN apt-get update && apt-get install -y clang-6.0
	WORKDIR /home/test/
	COPY ConsoleApplication1.cpp .
	RUN clang++-6.0 -pthread -std=c++17 ConsoleApplication1.cpp -o app
	CMD ["./app"]